version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ishop_db
      POSTGRES_USER: ishop_user
      POSTGRES_PASSWORD: ishop_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://ishop_user:ishop_pass@db/ishop_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: